package fpt.swp391.parkingmanagement.enums;

public enum IncidentType {
    LOST_TICKET,
    PLATE_MISMATCH,
    OVERTIME,
    WRONG_ZONE,
    UNPAID_EXIT,
    OTHER,
    SLOT_CONFLICT,
    RESERVATION_NO_SHOW,
    PAYMENT_EXCEPTION,
    UNAUTHORIZED_PARKING,
    MAINTENANCE_CONFLICT,
    DRIVER_LOST_TICKET,
    DRIVER_CANNOT_FIND_VEHICLE,
    DRIVER_INCORRECT_FEE,
    DRIVER_SLOT_OCCUPIED
}
