-- WARNING: Development-only helper. Do NOT use in production.
-- Adds a clear-text test password column and seeds four test users.
-- Replace <HASH_*> placeholders with real BCrypt hashes (see generate_bcrypt_hashes.py).

-- 1) add test_password column (nullable)
ALTER TABLE users
ADD COLUMN test_password VARCHAR(255) DEFAULT NULL;

-- 2) (optional) set email for existing admin if needed
-- UPDATE users SET email = 'admin@example.com' WHERE username = 'admin';

-- 3) Insert four new test users (usernames chosen to avoid collision)
-- Replace <HASH_ADMIN> etc with BCrypt hashes generated by the helper script.

INSERT INTO users (user_id, username, password_hash, test_password, full_name, email, role, status, is_active)
VALUES
  (UUID(), 'admin_test', '<HASH_ADMIN>', 'Admin@123', 'Admin Test', 'admin_test@example.com', 'ROLE_ADMIN', 'ACTIVE', TRUE),
  (UUID(), 'manager_test', '<HASH_MANAGER>', 'Manager@123', 'Manager Test', 'manager_test@example.com', 'ROLE_MANAGER', 'ACTIVE', TRUE),
  (UUID(), 'staff_test', '<HASH_STAFF>', 'Staff@123', 'Staff Test', 'staff_test@example.com', 'ROLE_STAFF', 'ACTIVE', TRUE),
  (UUID(), 'driver_test', '<HASH_DRIVER>', 'Driver@123', 'Driver Test', 'driver_test@example.com', 'ROLE_DRIVER', 'ACTIVE', TRUE);

-- If you already have users with same usernames, use UPDATE instead of INSERT:
-- Example (replace <HASH_ADMIN> first):
-- UPDATE users SET password_hash = '<HASH_ADMIN>', test_password = 'Admin@123', email='admin_test@example.com' WHERE username='admin';

-- After inserting/updating, you can login using the plaintext in test_password after setting password_hash to matching BCrypt value.

-- Cleanup reminder: remove test_password column and these seed users before deploying to production.
